version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: beer-game-proxy
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - ./config/dev-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      default:
        aliases:
          - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://127.0.0.1:8088/healthz | grep -q ok"]
      interval: 15s
      timeout: 5s
      retries: 4
      start_period: 10s

networks:
  default:
    name: beer-game-network
    external: true
