version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: beer-game-proxy
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      - ./config/dev-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - beer-game-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8088"]
      interval: 15s
      timeout: 5s
      retries: 4
      start_period: 10s

networks:
  beer-game-network:
    external: true
