version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.gpu
      args:
        - FORCE_GPU=1
    environment:
      - GPU_ENABLED=true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
