version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PORT=3306
      - MYSQL_USER=beer_user
      - MYSQL_PASSWORD=Daybreak@2025
      - MYSQL_DB=beer_game
      - SECRET_KEY=dev-secret-key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - DB_HOST=db
      - DB_USER=beer_user
      - DB_PASSWORD=Daybreak@2025
      - DB_NAME=beer_game
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: Daybreak@2025
      MYSQL_DATABASE: beer_game
      MYSQL_USER: beer_user
      MYSQL_PASSWORD: Daybreak@2025
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pDaybreak@2025"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_USER=beer_user
      - PMA_PASSWORD=Daybreak@2025
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
