services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: beer-game-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    networks:
      - beer-game-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: the_beer_game_backend
    restart: unless-stopped
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PORT=3306
      - MYSQL_USER=beer_user
      - MYSQL_PASSWORD=Daybreak2025
      - MYSQL_DB=beer_game
      - MYSQL_ROOT_PASSWORD=Daybreak2025
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - DB_CONNECTION_RETRIES=60
      - INIT_DB=true
      - DB_WAIT_TIMEOUT=30
      - DB_CONNECTION_TIMEOUT=30
      - PYTHONPATH=/app
      - DATABASE_URL=mysql+pymysql://beer_user:Daybreak2025@db:3306/beer_game
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      beer-game-network:
        aliases:
          - backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  db:
    image: mariadb:10.11
    container_name: the_beer_game_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: Daybreak2025
      MARIADB_DATABASE: beer_game
      MARIADB_USER: beer_user
      MARIADB_PASSWORD: Daybreak2025
      MARIADB_ROOT_HOST: '%'
      MARIADB_INITDB_SKIP_TZINFO: 1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./mariadb.cnf:/etc/mysql/conf.d/custom.cnf
      - ./scripts/init_database.sh:/docker-entrypoint-initdb.d/init_database.sh
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--max_connections=200',
      '--innodb-buffer-pool-size=256M',
      '--innodb-flush-log-at-trx-commit=1',
      '--innodb-flush-method=O_DIRECT',
      '--skip-log-bin',
      '--default-time-zone=+00:00',
      '--log-error=/var/log/mysql/error.log',
      '--general-log=0',
      '--slow-query-log=1',
      '--long-query-time=2',
      '--slow-query-log-file=/var/log/mysql/mariadb-slow.log'
    ]
    networks:
      - beer-game-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pDaybreak2025"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Daybreak2025
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - beer-game-network

  create-users:
    build:
      context: ./backend
      dockerfile: scripts/Dockerfile
    container_name: create-users
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PORT=3306
      - MYSQL_USER=beer_user
      - MYSQL_PASSWORD=Daybreak@2025
      - MYSQL_DB=beer_game
    depends_on:
      db:
        condition: service_healthy
    networks:
      - beer-game-network

networks:
  beer-game-network:
    driver: bridge

volumes:
  db_data:
